Update cf.yaml

diff --git a/.github/workflows/cf.yaml b/.github/workflows/cf.yaml
--- a/.github/workflows/cf.yaml
+++ b/.github/workflows/cf.yaml
@@ -1,4 +1,4 @@
-name: AWS CloudFormation Deployment
+name: Ant Media Server AWS CloudFormation Deployment
 
 on:
   push:
@@ -42,40 +42,38 @@ jobs:
                          ParameterKey=DashboardPassword,ParameterValue=admin \
                          ParameterKey=OriginInstanceType,ParameterValue=${{ env.ORIGIN_INSTANCE_TYPE }} \
                          ParameterKey=EdgeInstanceType,ParameterValue=${{ env.EDGE_INSTANCE_TYPE }} \
+                         ParameterKey=MongoDBInstanceType,ParameterValue=${{ env.MONGO_INSTANCE_TYPE }} \
                          ParameterKey=LoadBalancerCertificateArn,ParameterValue=${{ secrets.SSL_CERTIFICATE_ARN }} \
                          ParameterKey=AntMediaEdgeCapacity,ParameterValue=1 \
             --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
             --region ${{ env.AWS_REGION }}
-
-      - name: Display Stack Outputs
-        run: |
           timeout=$((SECONDS+420))
           while [ $SECONDS -lt $timeout ]; do
             sleep 10
             stack_status=$(aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} --query 'Stacks[0].StackStatus' --output text 2>&1)
             if [ "$stack_status" == "CREATE_COMPLETE" ]; then
               echo "Stack creation completed successfully."
-      
-              # Display Stack Outputs
-              outputs=$(aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} --query 'Stacks[0].Outputs' 2>&1)
-              status=$?
-              
-              if [ $status -ne 0 ]; then
-                echo "Failed to describe stack: $outputs"
-                exit 1
-              elif [ "$outputs" == "null" ]; then
-                echo "Stack Outputs are null. Deployment failed."
-                exit 1
-              else
-                echo "Stack Outputs: $outputs"
-              fi
-      
               break
             elif [ "$stack_status" == "ROLLBACK_COMPLETE" ] || [ "$stack_status" == "CREATE_FAILED" ]; then
               echo "Stack creation failed or rolled back."
               exit 1
             fi
           done
+
+      - name: Display Stack Outputs
+        run: |
+          outputs=$(aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} --query 'Stacks[0].Outputs' 2>&1)
+          status=$?
+          
+          if [ $status -ne 0 ]; then
+            echo "Failed to describe stack: $outputs"
+            exit 1
+          elif [ "$outputs" == "null" ]; then
+            echo "Stack Outputs are null. Deployment failed."
+            exit 1
+          else
+            echo "Stack Outputs: $outputs"
+          fi
       - name: Delete Stack
         if: ${{ always() }}
         run: |
