Update cf.yaml

diff --git a/.github/workflows/cf.yaml b/.github/workflows/cf.yaml
--- a/.github/workflows/cf.yaml
+++ b/.github/workflows/cf.yaml
@@ -55,6 +55,9 @@ jobs:
           if [ $status -ne 0 ]; then
             echo "Failed to describe stack: $outputs"
             exit 1
+          elif [ "$outputs" == "null" ]; then
+            echo "Stack Outputs are null. Deployment failed."
+            exit 1
           else
             echo "Stack Outputs: $outputs"
           fi
